timezone: Asia/Seoul

markdown: kramdown

highlighter: rouge

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: "tags"
    values:
      layout: "tag"